# Generated by Django 3.2.16 on 2023-06-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='\xa0Уникальное значение'),
        ),
    ]
